# Google Cloud App Engine configuration
runtime: python312

env_variables:
  FLASK_ENV: production
  PYTHONPATH: /app/src

automatic_scaling:
  min_instances: 1
  max_instances: 2

resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10

handlers:
- url: /.*
  script: auto

